---
- name: Finder - Allow quitting via âŒ˜ + Q; doing so will also hide desktop icons
  osx_defaults:
    domain: com.apple.finder
    key: QuitMenuItem
    type: bool
    value: true
    state: present
  notify: killall finder

- name: Finder - Show hidden files
  osx_defaults:
    domain: com.apple.finder
    key: AppleShowAllFiles
    type: bool
    value: true
    state: present
  notify: killall finder

- name: Finder - Show all filename extensions
  osx_defaults:
    domain: NSGlobalDomain
    key: AppleShowAllExtensions
    type: bool
    value: true
    state: present
  notify: killall finder

- name: Finder - Show status bar
  osx_defaults:
    domain: com.apple.finder
    key: ShowStatusBar
    type: bool
    value: true
    state: present
  notify: killall finder

- name: Finder - Show path bar
  osx_defaults:
    domain: com.apple.finder
    key: ShowPathbar
    type: bool
    value: true
    state: present

- name: Finder - Use list view in all Finder windows by default
  osx_defaults:
    domain: com.apple.finder
    key: FXPreferredViewStyle
    type: string
    value: Nlsv
    state: present
  notify: killall finder

- name: Finder - Keep folders on top when sorting by name
  osx_defaults:
    domain: com.apple.finder
    key: _FXSortFoldersFirst
    type: bool
    value: true
    state: present

- name: Finder - When performing a search, search the current folder by default
  osx_defaults:
    domain: com.apple.finder
    key: FXDefaultSearchScope
    type: string
    value: SCcf
    state: present
  notify: killall finder

- name: Finder - Disable the warning when changing a file extension
  osx_defaults:
    domain: com.apple.finder
    key: FXEnableExtensionChangeWarning
    type: bool
    value: false
    state: present
  notify: killall finder

- name: Finder - Disable disable Recent Tags
  osx_defaults:
    domain: com.apple.finder
    key: ShowRecentTags
    type: bool
    value: false
    state: present
  notify: killall finder

- name: Show the ~/Library folder
  command: chflags nohidden ~/Library
  changed_when: true
  notify: killall finder

- name: Show the /Volumes folder
  command: chflags nohidden /Volumes
  become: yes
  changed_when: true
  notify: killall finder