---
- name: Kill Dock
  ansible.builtin.command: killall Dock
  changed_when: false

- name: Kill Finder
  ansible.builtin.command: killall Finder
  changed_when: false

- name: Kill SystemUIServer
  ansible.builtin.command: killall SystemUIServer
  changed_when: false

- name: Kill WallpaperAgent
  ansible.builtin.command: killall WallpaperAgent
  changed_when: false
