---
- name: killall dock
  command: killall Dock
  become: yes
  ignore_errors: yes

- name: killall finder
  command: killall Finder
  become: yes
  ignore_errors: yes

- name: killall systemuiserver
  command: killall SystemUIServer
  become: yes
  ignore_errors: yes